/**
 * Floor plans generated by tools/mapstitch/build_floor.py from the stitched
 * screenshots. All coordinates are pixels of the stitched floor image.
 */

export type Point = { x: number; y: number };
export type Ring = [number, number][];

export type RoomCategory =
  | "lab"
  | "room"
  | "office"
  | "faculty"
  | "hall"
  | "food"
  | "washroom_men"
  | "washroom_women"
  | "building";

export type PlaceCategory = RoomCategory | "open" | "sports" | "garden" | "gate";

export type Side = "top" | "bottom" | "left" | "right";

export type RoomShape =
  | { type: "rect"; x: number; y: number; w: number; h: number }
  | { type: "poly"; points: Ring };

export type PlanRoom = {
  id: string;
  shape: RoomShape;
  bbox: [number, number, number, number];
  /** Absent for blocks the source map leaves unlabelled. */
  name?: string;
  lines?: string[];
  category?: RoomCategory;
  aliases?: string[];
  label?: { x: number; y: number; size: number };
  node?: number;
  /** Entrances offered where the source draws no door (one per side facing walkable space). */
  inferredEntrances?: { side: Side; x: number; y: number }[];
  /** Edges of the feature that no screenshot shows; drawn to the last visible pixel. */
  unseenEdges?: Side[];
};

export type PlanArea = {
  kind: "corridor" | "open" | "field" | "garden" | "passage";
  bbox: [number, number, number, number];
  rings: Ring[];
};

export type PlanDoor = { x: number; y: number; w: number; h: number; orientation: "h" | "v"; rooms: string[] };

export type PlanStairs = { id: string; bbox: [number, number, number, number]; rings: Ring[]; node?: number | null };

/** A gate marker; tall markers carry their label rotated (`rotate` degrees, clockwise). */
export type PlanGate = { id: string; name: string; aliases: string[]; bbox: [number, number, number, number]; node: number; label: { x: number; y: number; size: number; rotate?: number } };

export type PlanPlace = {
  id: string;
  name: string;
  category: PlaceCategory;
  aliases: string[];
  x: number;
  y: number;
  node: number;
  area?: "field" | "garden";
  bbox?: [number, number, number, number];
  /** Outline of a field or garden (its bbox is only the bounds). */
  rings?: Ring[];
  label?: { x: number; y: number; size: number; lines: string[] };
  inferredEntrances?: { side: Side; x: number; y: number }[];
  unseenEdges?: Side[];
};

export type NavNodeKind = "corner" | "approach" | "door" | "room" | "place" | "gate" | "stairs";

export type FloorPlan = {
  floor: { id: string; building: string; code: string; name: string; width: number; height: number; image: string };
  rooms: PlanRoom[];
  areas: PlanArea[];
  doors: PlanDoor[];
  stairs: PlanStairs[];
  gates: PlanGate[];
  places: PlanPlace[];
  nav: {
    clearance: number;
    outdoorCost: number;
    roomTransit: number;
    /** [x, y, kind, ref] — ref is the room/place/gate/stairs id for those kinds. */
    nodes: [number, number, NavNodeKind, string | null][];
    /** [a, b, weight, share of the segment outdoors, share through open areas such as the quad] */
    edges: [number, number, number, number, number][];
  };
  problems: string[];
};
